version: '3.8'

services:
  mysql:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: mysql8.4
    ports:
      - "${MYSQL_HOST_PORT}:3306"
      - "${MYSQL_HOST_X_PROTOCOL_PORT}:33060"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    restart: unless-stopped

volumes:
  mysql-data:
